FROM ros:humble-ros-base-jammy

RUN apt-get update && apt-get install -y \
    python3-colcon-common-extensions \
    python3-pip \





# Default entrypoint for the container
ENTRYPOINT ["/bin/bash"]